// 현재 Application에서 지원하는 Chain ID 리스트입니다.
export const AVAILABLE_CHAIN_IDS = [
  "agoric-3",
  "akashnet-2",
  "axelar-dojo-1",
  "bostrom",
  "phoenix-1",
  "core-1",
  "cosmoshub-4",
  "crypto-org-chain-mainnet-1",
  "emoney-3",
  "evmos_9001-2",
  "gravity-bridge-3",
  "iov-mainnet-ibc",
  "injective-1",
  "irishub-1",
  "ixo-4",
  "juno-1",
  "kava_2222-10",
  "mars-1",
  "osmosis-1",
  "quicksilver-2",
  "regen-1",
  "secret-4",
  "sentinelhub-2",
  "shentu-2.2",
  "sifchain-1",
  "sommelier-3",
  "stargaze-1",
  "stride-1",
  "umee-1",
  "quasar-1",
  "omniflixhub-1",
  "kyve-1",
  "noble-1",
  "neutron-1",
  "gitopia",
];

// Chain Registry를 가져오는 URL입니다.
export const CHAIN_REGISTRY_URL =
  "https://keplr-chain-registry.vercel.app/api/chains";
